#!/usr/bin/env python
#coding=utf8
'''
Created on 2016/9/16

@author: cloudy
'''
"""
Django settings for cim project.

Generated by 'django-admin startproject' using Django 1.8.14.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f7sf-4+2u3_vneb$bpb4rz(h(mb8tn3np!w&3edn%#p7e%0^af'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = (
    'django_admin_bootstrapped',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',#基础模块
    'performance',#绩效
    'career',#职业规划
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'cim.urls'
AUTH_USER_MODEL = 'base.User'

STATIC_ROOT = BASE_DIR +"/templates/"
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    'base/static',
    'cim/static',
    'performance/static',
    'career/static',
)
SESSION_ENGINE ='django.contrib.sessions.backends.db'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'base/templates',
            'cim/templates',
            'performance/templates',
            'career/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'cim',
        'USER': 'django',
        'PASSWORD': 'django',
        # 'HOST': '127.0.0.1',
        'HOST':'192.168.21.141',
        'PORT': '5432',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

FILE_CHARSET = 'utf-8'
DEFAULT_CHARSET = 'utf-8'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# BOOTSTRAP3 = {
#
#     # The URL to the jQuery JavaScript file
#     'jquery_url': '//code.jquery.com/jquery.min.js',
#
#     # The Bootstrap base URL
#     'base_url': '//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/',
#
#     # The complete URL to the Bootstrap CSS file (None means derive it from base_url)
#     'css_url': None,
#
#     # The complete URL to the Bootstrap CSS file (None means no theme)
#     'theme_url': None,
#
#     # The complete URL to the Bootstrap JavaScript file (None means derive it from base_url)
#     'javascript_url': None,
#
#     # Put JavaScript in the HEAD section of the HTML document (only relevant if you use bootstrap3.html)
#     'javascript_in_head': False,
#
#     # Include jQuery with Bootstrap JavaScript (affects django-bootstrap3 template tags)
#     'include_jquery': False,
#
#     # Label class to use in horizontal forms
#     'horizontal_label_class': 'col-md-3',
#
#     # Field class to use in horizontal forms
#     'horizontal_field_class': 'col-md-9',
#
#     # Set HTML required attribute on required fields
#     'set_required': True,
#
#     # Set HTML disabled attribute on disabled fields
#     'set_disabled': False,
#
#     # Set placeholder attributes to label if no placeholder is provided
#     'set_placeholder': True,
#
#     # Class to indicate required (better to set this in your Django form)
#     'required_css_class': '',
#
#     # Class to indicate error (better to set this in your Django form)
#     'error_css_class': 'has-error',
#
#     # Class to indicate success, meaning the field has valid input (better to set this in your Django form)
#     'success_css_class': 'has-success',
#
#     # Renderers (only set these if you have studied the source and understand the inner workings)
#     'formset_renderers':{
#         'default': 'bootstrap3.renderers.FormsetRenderer',
#     },
#     'form_renderers': {
#         'default': 'bootstrap3.renderers.FormRenderer',
#     },
#     'field_renderers': {
#         'default': 'bootstrap3.renderers.FieldRenderer',
#         'inline': 'bootstrap3.renderers.InlineFieldRenderer',
#     },
# }